import PropTypes from "prop-types";
import { Header } from "./header";
import { Container } from "@chakra-ui/react";
import Head from "next/head";
import { Footer } from "./footer";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>James Zechman {title ? "| " + title : "| Home"}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Container maxW='container.xl'>{children}</Container>
      <Footer />
    </>
  );
};

Layout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default Layout;
